# Generated by Django 5.2.10 on 2026-01-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_state', models.JSONField(default=list, verbose_name='Trạng thái bàn cờ')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
