# Generated by Django 5.2.10 on 2026-01-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='board_size',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='match',
            name='current_turn',
            field=models.CharField(default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='match',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='board_size',
            field=models.IntegerField(choices=[(15, '15x15'), (19, '19x19')], default=15),
        ),
    ]
